sonar.projectKey=ffreis-stock-simulator
sonar.organization=felipefuhr
sonar.projectName=ffreis-stock-simulator
sonar.sources=src
sonar.tests=tests
sonar.exclusions=src/stocksim_grpc/**
sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml
