# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from stocksim_grpc import engine_pb2 as stocksim__grpc_dot_engine__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in stocksim_grpc/engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EngineServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/stocksim.grpc.EngineService/Ping',
                request_serializer=stocksim__grpc_dot_engine__pb2.PingRequest.SerializeToString,
                response_deserializer=stocksim__grpc_dot_engine__pb2.PingResponse.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/stocksim.grpc.EngineService/Reset',
                request_serializer=stocksim__grpc_dot_engine__pb2.ResetRequest.SerializeToString,
                response_deserializer=stocksim__grpc_dot_engine__pb2.ResetResponse.FromString,
                _registered_method=True)
        self.Observe = channel.unary_unary(
                '/stocksim.grpc.EngineService/Observe',
                request_serializer=stocksim__grpc_dot_engine__pb2.ObserveRequest.SerializeToString,
                response_deserializer=stocksim__grpc_dot_engine__pb2.ObserveResponse.FromString,
                _registered_method=True)
        self.StepMany = channel.unary_unary(
                '/stocksim.grpc.EngineService/StepMany',
                request_serializer=stocksim__grpc_dot_engine__pb2.StepManyRequest.SerializeToString,
                response_deserializer=stocksim__grpc_dot_engine__pb2.StepManyResponse.FromString,
                _registered_method=True)


class EngineServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Observe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StepMany(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=stocksim__grpc_dot_engine__pb2.PingRequest.FromString,
                    response_serializer=stocksim__grpc_dot_engine__pb2.PingResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=stocksim__grpc_dot_engine__pb2.ResetRequest.FromString,
                    response_serializer=stocksim__grpc_dot_engine__pb2.ResetResponse.SerializeToString,
            ),
            'Observe': grpc.unary_unary_rpc_method_handler(
                    servicer.Observe,
                    request_deserializer=stocksim__grpc_dot_engine__pb2.ObserveRequest.FromString,
                    response_serializer=stocksim__grpc_dot_engine__pb2.ObserveResponse.SerializeToString,
            ),
            'StepMany': grpc.unary_unary_rpc_method_handler(
                    servicer.StepMany,
                    request_deserializer=stocksim__grpc_dot_engine__pb2.StepManyRequest.FromString,
                    response_serializer=stocksim__grpc_dot_engine__pb2.StepManyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stocksim.grpc.EngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stocksim.grpc.EngineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EngineService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stocksim.grpc.EngineService/Ping',
            stocksim__grpc_dot_engine__pb2.PingRequest.SerializeToString,
            stocksim__grpc_dot_engine__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stocksim.grpc.EngineService/Reset',
            stocksim__grpc_dot_engine__pb2.ResetRequest.SerializeToString,
            stocksim__grpc_dot_engine__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Observe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stocksim.grpc.EngineService/Observe',
            stocksim__grpc_dot_engine__pb2.ObserveRequest.SerializeToString,
            stocksim__grpc_dot_engine__pb2.ObserveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StepMany(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stocksim.grpc.EngineService/StepMany',
            stocksim__grpc_dot_engine__pb2.StepManyRequest.SerializeToString,
            stocksim__grpc_dot_engine__pb2.StepManyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
