name: Semgrep Code Analysis

permissions: {}

on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  semgrep:
    permissions:
      contents: read
    uses: FelipeFuhr/ffreis-workflows-python/.github/workflows/python-semgrep.yml@8405bfc6e887b6e1af634a6ed104538ab98d3baf # main (post-#98)
